import type { B2BProductSubmission } from "@/lib/b2b-types";

const defaults = {
  photos: [] as string[],
  sku: "",
  lowStockAlert: 5,
  sizes: [] as string[],
  colours: [] as string[],
  courierPackageSize: "Medium" as const,
  tags: [] as string[],
  newArrival: false,
  hotSale: false,
  hotDiscount: 0,
  todaysDeal: false,
  dealStart: "",
  dealEnd: "",
  outOfStock: false,
};

export const b2bSubmissionSeed: B2BProductSubmission[] = [
  {
    ...defaults,
    id: "SUB-3001",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    name: "Himal Grain-Free Adult Dog Food 3kg",
    desc: "Locally packed grain-free kibble for adult dogs, chicken & rice recipe.",
    category: "Pet Food",
    brand: "Himal",
    price: 2450,
    qty: 40,
    commissionPct: 15,
    status: "Approved",
    submittedAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
  },
  {
    ...defaults,
    id: "SUB-3002",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    name: "Himal Cat Litter Clumping 5L",
    desc: "Bentonite clumping litter, low dust, odor control.",
    category: "Pet Supplement",
    brand: "Himal",
    price: 890,
    qty: 60,
    commissionPct: 12,
    status: "Pending",
    submittedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    ...defaults,
    id: "SUB-3003",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    name: "Himal Reflective Dog Collar M",
    desc: "Nylon reflective collar, medium, adjustable 30-45cm.",
    category: "Pet Accessories",
    brand: "Himal",
    price: 450,
    qty: 25,
    commissionPct: 20,
    status: "Rejected",
    submittedAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
  },
];
