import type { DogBreed } from "./dog-breed-types";

export const dogBreedSeed: DogBreed[] = [
  {
    id: "breed-labrador",
    name: "Labrador Retriever",
    photo: "",
    origin: "United Kingdom",
    size: "Large",
    lifespan: "10–12 years",
    coat: "Short, dense, water-resistant",
    temperament: "Friendly, outgoing, and eager to please — one of the easiest breeds to train.",
    goodWith: "Families, children, first-time owners",
    exercise: "High — daily walks plus play",
    grooming: "Low — weekly brushing, sheds seasonally",
    description:
      "A steady, food-motivated family favorite that thrives on activity and companionship. Their friendly nature makes them a reliable choice for households with kids or other pets.",
  },
  {
    id: "breed-gsd",
    name: "German Shepherd",
    photo: "",
    origin: "Germany",
    size: "Large",
    lifespan: "9–13 years",
    coat: "Medium-length double coat",
    temperament: "Loyal, confident, and highly trainable — a natural protector.",
    goodWith: "Active families, experienced owners",
    exercise: "High — needs a job or daily mental work",
    grooming: "Moderate — brush 2–3 times a week, heavy seasonal shedding",
    description:
      "Widely used for guarding and working roles thanks to their intelligence and courage. Consistent training and early socialization bring out their best temperament.",
  },
  {
    id: "breed-golden",
    name: "Golden Retriever",
    photo: "",
    origin: "Scotland",
    size: "Large",
    lifespan: "10–12 years",
    coat: "Dense, water-repellent, wavy",
    temperament: "Gentle, patient, and affectionate with everyone they meet.",
    goodWith: "Families, children, other pets",
    exercise: "High — loves swimming and fetch",
    grooming: "Moderate to high — brush several times a week",
    description:
      "One of the most even-tempered breeds around, often used as a therapy and guide dog. Their playful, forgiving nature suits busy households well.",
  },
  {
    id: "breed-pomeranian",
    name: "Pomeranian",
    photo: "",
    origin: "Germany/Poland",
    size: "Small (toy)",
    lifespan: "12–16 years",
    coat: "Thick double coat, fluffy",
    temperament: "Bold, alert, and lively — often unaware of their small size.",
    goodWith: "Apartment living, singles, older children",
    exercise: "Low to moderate — short walks and play",
    grooming: "High — daily brushing to prevent matting",
    description:
      "A compact companion with a big personality, popular for apartment life in Kathmandu. Their alertness makes them enthusiastic (if vocal) little watchdogs.",
  },
  {
    id: "breed-lhasa",
    name: "Lhasa Apso",
    photo: "",
    origin: "Tibet",
    size: "Small",
    lifespan: "12–15 years",
    coat: "Long, dense, straight",
    temperament: "Independent, watchful, and a little aloof with strangers.",
    goodWith: "Apartments, calmer households",
    exercise: "Low to moderate — daily short walks",
    grooming: "High — regular brushing or a shorter trim",
    description:
      "Bred as monastery watchdogs in Tibet, they carry a confident, alert temperament in a small frame. Well suited to Kathmandu's cooler climate.",
  },
  {
    id: "breed-pug",
    name: "Pug",
    photo: "",
    origin: "China",
    size: "Small",
    lifespan: "12–15 years",
    coat: "Short, smooth",
    temperament: "Playful, affectionate, and sociable with people and pets alike.",
    goodWith: "Apartments, families, first-time owners",
    exercise: "Low — short walks, avoid heat",
    grooming: "Low — weekly brushing, clean facial folds",
    description:
      "A charming, easygoing companion suited to smaller homes. Their short muzzle means they need protection from heat and heavy exertion.",
  },
  {
    id: "breed-rottweiler",
    name: "Rottweiler",
    photo: "",
    origin: "Germany",
    size: "Large",
    lifespan: "9–10 years",
    coat: "Short, dense, coarse",
    temperament: "Confident, alert, and deeply loyal to their family.",
    goodWith: "Experienced owners, space to move",
    exercise: "High — structured exercise and training",
    grooming: "Low — weekly brushing",
    description:
      "A powerful guardian breed that needs firm, consistent training from puppyhood. With proper socialization they are calm, devoted family protectors.",
  },
  {
    id: "breed-husky",
    name: "Siberian Husky",
    photo: "",
    origin: "Siberia, Russia",
    size: "Medium to large",
    lifespan: "12–14 years",
    coat: "Thick double coat",
    temperament: "Energetic, friendly, and independent-minded.",
    goodWith: "Active owners, cooler climates",
    exercise: "Very high — needs a real outlet daily",
    grooming: "Moderate to high — heavy seasonal shedding",
    description:
      "Bred to run for miles, huskies need serious daily exercise and a securely fenced space. Their striking looks come with a strong-willed, independent streak.",
  },
  {
    id: "breed-beagle",
    name: "Beagle",
    photo: "",
    origin: "United Kingdom",
    size: "Small to medium",
    lifespan: "12–15 years",
    coat: "Short, dense",
    temperament: "Curious, friendly, and driven by their nose.",
    goodWith: "Families, children, other dogs",
    exercise: "Moderate to high — enjoys sniffing walks",
    grooming: "Low — weekly brushing",
    description:
      "A merry, food-loving scent hound that gets along easily with people and other dogs. Secure fencing helps, as their nose can lead them astray.",
  },
  {
    id: "breed-dachshund",
    name: "Dachshund",
    photo: "",
    origin: "Germany",
    size: "Small",
    lifespan: "12–16 years",
    coat: "Smooth, wire, or long-haired",
    temperament: "Bold, curious, and surprisingly stubborn for their size.",
    goodWith: "Apartments, adult households",
    exercise: "Low to moderate — gentle daily walks",
    grooming: "Low to moderate depending on coat type",
    description:
      "Originally bred to hunt burrowing animals, their long back means jumping and stairs should be limited to protect their spine.",
  },
  {
    id: "breed-bhotekukur",
    name: "Himalayan Sheepdog (Bhote Kukur)",
    photo: "",
    origin: "Nepal",
    size: "Large",
    lifespan: "10–12 years",
    coat: "Thick, weather-resistant double coat",
    temperament: "Watchful, hardy, and fiercely loyal to their family.",
    goodWith: "Rural or hillside homes, experienced owners",
    exercise: "Moderate to high — bred to patrol open ground",
    grooming: "Moderate — brush weekly, sheds seasonally",
    description:
      "A native Nepali guardian breed well adapted to hill and mountain climates. Naturally protective, they do best with space and a clear role to fulfil.",
  },
  {
    id: "breed-chowchow",
    name: "Chow Chow",
    photo: "",
    origin: "China",
    size: "Medium to large",
    lifespan: "9–15 years",
    coat: "Thick, rough or smooth double coat",
    temperament: "Dignified, independent, and reserved with strangers.",
    goodWith: "Calmer households, experienced owners",
    exercise: "Moderate — daily walks, avoid heat",
    grooming: "High — frequent brushing to manage the dense coat",
    description:
      "Known for their distinctive blue-black tongue and lion-like mane, Chow Chows are aloof but deeply devoted to their own family.",
  },
];
