import type { PetTag, PetTagPageContent } from "@/lib/pet-tag-types";

export const petTagSeed: PetTag[] = [
  {
    id: "pt-1",
    tagId: "9ZG36R6B",
    petName: "Cooki",
    sex: "Male",
    age: "4 months",
    breed: "German Shepard",
    color: "Black & Tan",
    microchip: "900215001987654",
    notes: "",
    ownerName: "Shyam Gurung",
    phone: "+977 9851313717",
    altPhone: "9818608340",
    address: "",
    mapLink: "",
    scans: 10,
  },
  {
    id: "pt-2",
    tagId: "79VHFBPM",
    petName: "Uni",
    sex: "Male",
    age: "5 years, 10 months",
    breed: "Japanese Spitz",
    color: "White",
    microchip: "",
    notes: "",
    ownerName: "Sabita Thapa",
    phone: "+977 9842760300",
    altPhone: "",
    address: "",
    mapLink: "",
    scans: 6,
  },
  {
    id: "pt-3",
    tagId: "T1EHDCF",
    petName: "Maggie",
    sex: "Female",
    age: "6 years, 7 months",
    breed: "Golden Retriever",
    color: "Golden",
    microchip: "",
    notes: "",
    ownerName: "Shyam Gurung",
    phone: "+977 9851313717",
    altPhone: "9818608340",
    address: "",
    mapLink: "",
    scans: 0,
  },
  {
    id: "pt-4",
    tagId: "52D0FPCO",
    petName: "Molly",
    sex: "Female",
    age: "6 years, 7 months",
    breed: "Golden Retriever",
    color: "Golden",
    microchip: "",
    notes: "",
    ownerName: "Shyam Gurung",
    phone: "+977 9851313717",
    altPhone: "9818608340",
    address: "",
    mapLink: "",
    scans: 13,
  },
  {
    id: "pt-5",
    tagId: "95CC9CK5",
    petName: "Shree",
    sex: "Female",
    age: "6 years, 7 months",
    breed: "Doberman",
    color: "Black & Tan",
    microchip: "",
    notes: "",
    ownerName: "Shyam Gurung",
    phone: "+977 9851313717",
    altPhone: "9818608340",
    address: "",
    mapLink: "",
    scans: 2,
  },
];

export const petTagContentSeed: PetTagPageContent = {
  bannerTitle: "Pet Tag Archive",
  bannerSubtitle: "Reuniting pets wearing City Pet House QR tags with their families.",
  searchCaption: "Found a pet wearing a City Pet House tag? Enter the tag code printed on it (or the pet's name) to reach the owner.",
  sections: [
    {
      id: "sec-1",
      heading: "What is a City Pet House pet tag?",
      body: "Every pet tag we issue carries a unique QR code linked to the pet's profile in our system. Scanning it with any phone camera instantly shows the pet's details and the owner's contact information — no app required.",
    },
    {
      id: "sec-2",
      heading: "Why use a QR pet tag?",
      body: "A printed phone number can fade or become unreadable, but a QR tag stays scannable and always points to the latest contact details on file — update your phone number once in your account and every tag updates automatically.",
    },
    {
      id: "sec-3",
      heading: "How do I get one for my pet?",
      body: "Visit City Pet House or register through the app to have a tag generated for your pet. We print and attach it to a collar-ready tag you can pick up the same day.",
    },
    {
      id: "sec-4",
      heading: "Found a pet wearing one of our tags?",
      body: "Scan the QR code with your phone's camera, or enter the tag code above, to see the pet's details and reach the owner directly.",
    },
  ],
  faqs: [
    {
      id: "faq-1",
      q: "Does the QR tag track my pet's location?",
      a: "No. The tag only stores an ID that looks up the profile in our system — it has no GPS or tracking capability.",
    },
    {
      id: "faq-2",
      q: "What if my pet loses the tag?",
      a: "Contact us to have a replacement tag printed with the same profile — there's no need to re-register your pet's details.",
    },
    {
      id: "faq-3",
      q: "Can I update my contact details later?",
      a: "Yes — updating your phone number or address in your account updates every tag linked to your pets instantly.",
    },
  ],
};
