import type { RestockOrder } from "@/lib/restock-types";

export const restockOrderSeed: RestockOrder[] = [
  {
    id: "RS-9001",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    productId: "himal-grain-free-adult-dog-food-3kg",
    productName: "Himal Grain-Free Adult Dog Food 3kg",
    qty: 30,
    unitPrice: 2450,
    note: "Running low — please confirm you can supply this batch.",
    initiatedBy: "Admin",
    status: "Pending",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: "RS-9002",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    productId: "himal-puppy-starter-formula-1kg",
    productName: "Himal Puppy Starter Formula 1kg",
    qty: 50,
    unitPrice: 980,
    note: "We have fresh stock ready if you'd like to top up.",
    initiatedBy: "Supplier",
    status: "Accepted",
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    respondedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: "RS-9003",
    b2bId: "B2B-1001",
    companyName: "Himal Pet Supplies Pvt. Ltd.",
    productId: "himal-cat-litter-clumping-5l",
    productName: "Himal Cat Litter Clumping 5L",
    qty: 60,
    unitPrice: 890,
    note: "",
    initiatedBy: "Admin",
    status: "Delivered",
    createdAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    respondedAt: Date.now() - 17 * 24 * 60 * 60 * 1000,
    dispatchedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    deliveredAt: Date.now() - 13 * 24 * 60 * 60 * 1000,
  },
];
