export const siteSettings = {
  businessName: "City Pet House & Animal Clinic",
  shortName: "City Pet House",
  phone: "+977 9851313717",
  address: "Boudha Pipal Bot, Aryal Gaun, Gokarneshwor-6, Kathmandu",
  email: "citypethouse@gmail.com",
  hours: "9am – 7pm, Sun–Sat",
  facebook: "#",
  instagram: "#",
  tiktok: "#",
  youtube: "#",
  vaccinationAppStoreUrl: "#",
  vaccinationGooglePlayUrl: "#",
  shoppingAppLabel: "Download the PasuSewa App",
  shoppingAppStoreUrl: "#",
  shoppingGooglePlayUrl: "#",
};
